# Use a imagem oficial do PostgreSQL como base
FROM postgres:latest

# Defina variáveis de ambiente para o PostgreSQL
ENV POSTGRES_DB=meubanco
ENV POSTGRES_USER=meuusuario
ENV POSTGRES_PASSWORD=minhasenha

# O Dockerfile não precisa de mais instruções porque a imagem do PostgreSQL
# já contém tudo que é necessário para executar o PostgreSQL.